---
services:
  application:
    image: test-app:latest
    restart: unless-stopped
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql://test-app:testLocal@postgres:5432/test-app
      - OTEL_SERVICE_NAME=test-app
      - OTEL_PROPAGATORS=baggage
      - OTEL_PYTHON_EXCLUDED_URLS="ready,health"
      - OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SANITIZE_FIELDS=".*session.*,set-cookie"
      - OTEL_TRACES_EXPORTER=console
      - OTEL_TRACES_SAMPLER=traceidratio
      - OTEL_TRACES_SAMPLER_ARG=1
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console

    user: '${DOCKER_UID}:${DOCKER_GID}'
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    ports:
      - '5000:5000'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test-app
      POSTGRES_PASSWORD: testLocal
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
